/*
 * This file was automatically generated by EvoSuite
 * Sat Sep 19 13:52:29 GMT 2026
 */

package evosuiteTests;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.DeterministicTileStrategy;
import java.util.LinkedHashSet;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class DeterministicTileStrategy_ESTest extends DeterministicTileStrategy_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DeterministicTileStrategy deterministicTileStrategy0 = new DeterministicTileStrategy();
      // Undeclared exception!
      try { 
        deterministicTileStrategy0.determinarPosicion((Set<Board.Position>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.DeterministicTileStrategy", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DeterministicTileStrategy deterministicTileStrategy0 = new DeterministicTileStrategy();
      LinkedHashSet<Board.Position> linkedHashSet0 = new LinkedHashSet<Board.Position>();
      Board.Position board_Position0 = new Board.Position((-1), (-4195));
      Board.Position board_Position1 = new Board.Position((-1), 0);
      linkedHashSet0.add(board_Position1);
      linkedHashSet0.add(board_Position0);
      Board.Position board_Position2 = deterministicTileStrategy0.determinarPosicion(linkedHashSet0);
      assertNotNull(board_Position2);
      assertEquals((-4195), board_Position2.col);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedHashSet<Board.Position> linkedHashSet0 = new LinkedHashSet<Board.Position>();
      Board.Position board_Position0 = new Board.Position((-50), (-50));
      linkedHashSet0.add(board_Position0);
      Board.Position board_Position1 = new Board.Position((-20), (-50));
      linkedHashSet0.add(board_Position1);
      DeterministicTileStrategy deterministicTileStrategy0 = new DeterministicTileStrategy();
      Board.Position board_Position2 = deterministicTileStrategy0.determinarPosicion(linkedHashSet0);
      assertEquals((-50), board_Position2.row);
      assertNotNull(board_Position2);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DeterministicTileStrategy deterministicTileStrategy0 = new DeterministicTileStrategy();
      LinkedHashSet<Board.Position> linkedHashSet0 = new LinkedHashSet<Board.Position>();
      Board.Position board_Position0 = new Board.Position(3, 3);
      linkedHashSet0.add(board_Position0);
      Board.Position board_Position1 = new Board.Position((-1), (-4195));
      linkedHashSet0.add(board_Position1);
      Board.Position board_Position2 = deterministicTileStrategy0.determinarPosicion(linkedHashSet0);
      assertNotNull(board_Position2);
      assertEquals((-1), board_Position2.row);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DeterministicTileStrategy deterministicTileStrategy0 = new DeterministicTileStrategy();
      LinkedHashSet<Board.Position> linkedHashSet0 = new LinkedHashSet<Board.Position>();
      Board.Position board_Position0 = new Board.Position((-30), (-30));
      linkedHashSet0.add(board_Position0);
      Board.Position board_Position1 = new Board.Position((-30), 19);
      linkedHashSet0.add(board_Position1);
      Board.Position board_Position2 = deterministicTileStrategy0.determinarPosicion(linkedHashSet0);
      assertEquals((-30), board_Position2.col);
      assertNotNull(board_Position2);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DeterministicTileStrategy deterministicTileStrategy0 = new DeterministicTileStrategy();
      LinkedHashSet<Board.Position> linkedHashSet0 = new LinkedHashSet<Board.Position>();
      Board.Position board_Position0 = deterministicTileStrategy0.determinarPosicion(linkedHashSet0);
      assertNull(board_Position0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      DeterministicTileStrategy deterministicTileStrategy0 = new DeterministicTileStrategy();
      int int0 = deterministicTileStrategy0.determinarValor();
      assertEquals(2, int0);
  }
}
